version: '3.8'

services:
    node_api1:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '4001:4000'
        environment:
            - NODE_ENV=production

    node_api2:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '4002:4000'
        environment:
            - NODE_ENV=production

    node_api3:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '4003:4000'
        environment:
            - NODE_ENV=production

    node_api4:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '4004:4000'
        environment:
            - NODE_ENV=production
